server:
  port: 8001

spring:
  application:
    name:  @project.artifactId@

# 配置 eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    prefer-ip-address: true            # 表示将自己的 IP 注册到 Eureka Server 。默认为 false 则表示注册微服务所在的操作系统的 hostname 到 Eureka Server

info:
  app:
    name: @project.artifactId@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

microservice-simple-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  # 配置 IRule 的实现类
    #   NFLoadBalancerClassName 配置 ILoadBlancer 的实现类
    #   NFLoadBalancerPingClassName 配置 IPing 的实现类
    #   NIWSServerListClassName 配置 ServerList 的实现类
    #   NIWSServerListFilterClassName 配置 ServerListFilter 的实现类
    