server:
  port: 8764
eureka:
  client:
    register-with-eureka: false                      # 表示是否将自己注册到 Eureka Server ，默认为true
    fetch-registry: false                            # 表示是否从 Eureka Server 获取注册信息，默认为 true
    service-url:
      defaultZone: http://user:password123@localhost:8764/eureka/    # 设置与 Eureka Server 交互的地址，查询服务和注册服务都需要依赖这个地址

spring:
  security:
    basic:
      enabled: true                    # 开启基于 HTTP base 的认证
    user:
      name: user                       # 配置登录的账号是user
      password: password123            # 配置登录的密码是password123